# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b619b5623d3b56101a9fbd5dd7186394ecfa2718136e0c41131797f5f2a36b6961722a56cf78d3607f84dd4e40bde383e4ecc07131ea88f6bcbcfc656193dcd

test:
  secret_key_base: 917bba664212016e7d5334155ddd163f36c23587b6b781c122eac66676bd5845dc6e06cf79101303f2d76cd6610cc10eb13d68a836c723b5d69808351f1fd418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
